#ifndef SYSTEMLIB_PLATFORM_H
#define SYSTEMLIB_PLATFORM_H

enum ePlatform
{
	PLATFORM_OPENGL = 0,
	PLATFORM_OPENGLES2 = 1,
	PLATFORM_D3D9 = 2,
	PLATFORM_XBOX360 = 3,
	PLATFORM_PS3 = 4,
	PLATFORM_PS4 = 5,
	NUM_PLATFORMS,
};

#endif
